-- DROP DATABASE IF EXISTS ROOMSAMENITIES;
-- CREATE DATABASE ROOMSAMENITIES;

DROP TABLE IF EXISTS Rooms;

CREATE TABLE Rooms (
  ID SERIAL NOT NULL PRIMARY KEY ,
  roomname VARCHAR(255),
  selfCheckIn BOOLEAN NOT NULL,
  pool BOOLEAN NOT NULL,
  kitchen BOOLEAN NOT NULL,
  washer BOOLEAN NOT NULL,
  dryer BOOLEAN NOT NULL,
  dishWasher BOOLEAN NOT NULL,
  indoorFireplace BOOLEAN NOT NULL,
  petsAllowed BOOLEAN NOT NULL,
  heating BOOLEAN NOT NULL,
  airConditioning BOOLEAN NOT NULL,
  wifi BOOLEAN NOT NULL,
  TV BOOLEAN NOT NULL,
  bathroomEssentials BOOLEAN NOT NULL,
  bedroomComforts BOOLEAN NOT NULL,
  coffeeMaker BOOLEAN NOT NULL,
  hairDryer BOOLEAN NOT NULL,
  iron BOOLEAN NOT NULL,
  carbonMonoxideDetector BOOLEAN NOT NULL,
  smokeDetector BOOLEAN NOT NULL
);
